# Generated by Django 2.2 on 2020-08-16 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workplace', '0003_permissions_prepermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0019_auto_20200813_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teammessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messsagetype', models.IntegerField()),
                ('message', models.CharField(max_length=500)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workplace.Team')),
                ('tuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Touser', to=settings.AUTH_USER_MODEL)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commentmessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messsagetype', models.IntegerField(default=8)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=500)),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.ArticlePost')),
                ('tuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Couser', to=settings.AUTH_USER_MODEL)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
