# Generated by Django 2.2 on 2020-08-16 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmessage',
            old_name='messsagetype',
            new_name='messagetype',
        ),
        migrations.RenameField(
            model_name='teammessage',
            old_name='messsagetype',
            new_name='messagetype',
        ),
    ]
