# Generated by Django 2.2 on 2020-08-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20200816_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmessage',
            name='messagetype',
            field=models.IntegerField(default=9),
        ),
    ]
