# Generated by Django 2.2 on 2020-08-04 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_articlepost_total_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlepost',
            old_name='total_view',
            new_name='total_views',
        ),
    ]
