# Generated by Django 2.2 on 2020-08-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_articlepost_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepost',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='articlepost',
            name='column',
        ),
        migrations.RemoveField(
            model_name='articlepost',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='articlepost',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='articlepost',
            name='total_views',
        ),
        migrations.AddField(
            model_name='articlepost',
            name='last_updater',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
