# Generated by Django 2.2 on 2020-08-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_articlepost_is_in_garbage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='is_in_garbage',
            field=models.IntegerField(),
        ),
    ]
