# Generated by Django 2.2 on 2020-08-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='permission',
            field=models.IntegerField(default=0),
        ),
    ]
