# Generated by Django 2.2 on 2020-08-13 09:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0017_updatingrecord'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UpdatingRecord',
            new_name='WatchingRecord',
        ),
    ]
