# Generated by Django 2.2 on 2020-08-13 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0018_auto_20200813_0941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchingrecord',
            options={'ordering': ('-record_date',)},
        ),
    ]
