# Generated by Django 2.2 on 2020-08-14 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('tname', models.CharField(max_length=50)),
                ('tnum', models.PositiveIntegerField()),
                ('tcreatetime', models.DateTimeField(auto_now_add=True)),
                ('tcreateuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workplace.Users')),
                ('tmem', models.ManyToManyField(related_name='user', to='workplace.Users')),
            ],
        ),
    ]
