# Generated by Django 2.2 on 2020-08-16 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0019_auto_20200813_0948'),
        ('workplace', '0002_auto_20200814_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prepermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(blank=True)),
                ('tid', models.IntegerField(blank=True)),
                ('did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.ArticlePost')),
            ],
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.IntegerField(blank=True)),
                ('tid', models.IntegerField(blank=True)),
                ('did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.ArticlePost')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
